---
# Install Nginx server
- name: Install nginx web server
  apt: pkg=nginx state=installed update_cache=true
  notify:
    - start nginx

- name: Ensure nginx is installed
  apt:
      name: "{{ nginx_package_name }}"
      state: installed
      default_release: "{{ nginx_default_release }}"
