---
# Variable Setup
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup PHP on environment
- include: setup-Debian.yml
  when: ansible_os_family == "Debian"
  static: no

# Configure PHP
- include: configure.yml
  static: no
