---
# defaults file for php
dotdeb_apt_host: 'packages.dotdeb.org'
dotdeb_apt_src: false
dotdeb_wheezy_php_version: null

# PHP package state; use 'installed' to make sure it's installed, or 'latest' if
# you want to upgrade or switch versions using a new repo.
php_packages_state: installed

# Whether to install recommended packages. Used only for Debian/Ubuntu.
php_install_recommends: no

php_sendmail_path: sendmail -t -i

# Ini file configuration
php_ini_fpm: php_fpm.ini.j2
php_ini_cli: php_cli.ini.j2
php_opcache_file: opcache.ini.j2

# OpCache settings (useful for PHP >=5.5).
php_opcache_zend_extension: "opcache.so"
php_opcache_enable: "1"
php_opcache_enable_cli: "0"
php_opcache_memory_consumption: "128"
php_opcache_interned_strings_buffer: "16"
php_opcache_max_accelerated_files: "4096"
php_opcache_max_wasted_percentage: "10"
php_opcache_validate_timestamps: "0"
php_opcache_revalidate_path: "0"
php_opcache_revalidate_freq: "2"
php_opcache_max_file_size: "0"
php_opcache_blacklist_filename: ""
